### 0. 公开接口（应返回 200）
GET http://localhost:8080/api/hello
###

### 1. 未登录访问（应返回 40101）
GET http://localhost:8080/api/me

###

### 2. 携带非法 Token（应返回 401）
GET http://localhost:8080/api/me
Authorization: Bearer abc.def.xxx

###


### 3.登录（user）
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "123456"
}


> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}
###

### 4.登录（admin）
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

###

### 5.退出
POST http://localhost:8080/auth/logout
Authorization: Bearer {{token}}
###


### 6.刷新token
POST http://localhost:8080/auth/refresh
Authorization: Bearer {{refresh_token}}

> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}
###



### ========== 功能权限验证 - spring注解 ==========
### 7.admin接口（admin 有权限）
POST http://localhost:8080/api/admin/spring
Authorization: Bearer {{token}}

###

### 8.查询接口（user、admin有权限）
GET http://localhost:8080/api/query/spring
Authorization: Bearer {{token}}

###

### 9.新增接口（user 无权限，应 403）
POST http://localhost:8080/api/add/spring
Authorization: Bearer {{token}}

###

### ========== 功能权限验证 - 自定义注解 ==========
### 10.查询接口（admin 有权限）
POST http://localhost:8080/api/admin/starter
Authorization: Bearer {{token}}

###

### 11.新增接口（user、admin有权限）
GET http://localhost:8080/api/query/starter
Authorization: Bearer {{token}}

###

### 12.查询接口（admin 有权限）
POST http://localhost:8080/api/add/starter
Authorization: Bearer {{token}}

###





